# =========================================================
# DEFINICIÓN DE MÓDULOS
# =========================================================
from typing import Any, Dict

MODULES: Dict[str, Dict[str, Any]] = {
    "Caja VMR": {
        "table": "caja_vmr",
        "empresa": "VMR",
        "tipo": "flujo",
        "descripcion": "Movimientos de efectivo de Vitae Medicina Reproductiva.",
        "fields": [
            ("fecha", "date", True),
            ("concepto", "text", True),
            ("categoria", "select", True, ["Ingreso", "Egreso", "Retiro", "Aporte", "Otro"]),
            ("medio", "select", True, ["Efectivo", "Transferencia", "Tarjeta", "Cheque", "Otro"]),
            ("ingreso", "money", False),
            ("egreso", "money", False),
            ("responsable", "text", False),
            ("observaciones", "textarea", False),
        ],
    },
    "Banco Macro VMR": {
        "table": "banco_macro_vmr",
        "empresa": "VMR",
        "tipo": "flujo",
        "descripcion": "Movimientos bancarios de Banco Macro pertenecientes a VMR.",
        "fields": [
            ("fecha", "date", True),
            ("concepto", "text", True),
            ("tipo_movimiento", "select", True, ["Crédito", "Débito", "Transferencia", "Débito automático", "Impuesto", "Otro"]),
            ("referencia", "text", False),
            ("ingreso", "money", False),
            ("egreso", "money", False),
            ("conciliado", "bool", False),
            ("observaciones", "textarea", False),
        ],
    },
    "Cuenta Corriente VMR": {
        "table": "cuenta_corriente_vmr",
        "empresa": "VMR",
        "tipo": "cuenta_corriente",
        "descripcion": "Cuentas por cobrar y pagar de VMR.",
        "fields": [
            ("fecha", "date", True),
            ("persona_entidad", "text", True),
            ("concepto", "text", True),
            ("tipo", "select", True, ["A cobrar", "A pagar"]),
            ("importe", "money", True),
            ("pagado", "money", False),
            ("vencimiento", "date", False),
            ("estado", "select", True, ["Pendiente", "Parcial", "Pagado", "Vencido"]),
            ("observaciones", "textarea", False),
            ("saldo", "number", "Saldo $"),
            ("importe_usd", "number", "Importe USD"),
            ("saldo_usd", "number", "Saldo USD"),
        ],
    },

    "Agenda Quirófano": {

        "table": "agenda_quirofano",
    
        "empresa": "VM",
    
        "tipo": "quirófano",
    
        "descripcion": "Agenda diaria, semanal y mensual de cirugías.",
    
        "fields": [

        ("fecha", "date", True),
    
        ("hora_inicio", "text", True),
    
        ("hora_fin", "text", True),
    
        ("duracion_min", "number", True),
    
        ("sala", "select", True, ["Quirófano 1"]),
    
        ("paciente", "text", True),
    
        ("procedimiento", "text", True),
    
        ("medico", "text", True),
    
        ("anestesista", "text", False),
    
        ("estado", "select", True,
    
         ["Programada", "En curso", "Finalizada", "Suspendida", "Cancelada"]),
    
        ("observaciones", "textarea", False),
    
    ],
  },
    "Facturación VMR": {
        "table": "facturacion_vmr",
        "empresa": "VMR",
        "tipo": "facturacion",
        "descripcion": "Control de facturación de procedimientos/pacientes de VMR según planilla quirófano.",
        "fields": [
            ("mes", "date", True),
            ("afiliado", "text", True),
            ("obra_social", "text", True),
            ("procedimiento", "text", True),
            ("medico_responsable", "text", True),
            ("fecha_factura", "date", False),
            ("numero_factura", "text", False),
            ("vencimiento", "date", False),
            ("fecha_pago", "text", False),
            ("valor_pesos", "money", False),
            ("valor_usd", "money", False),
            ("estado", "select", True, ["Pendiente", "Completo", "Parcial", "Vencido", "Anulado"]),
            ("observaciones", "textarea", False),
        ],
    },
    "Caja VM": {
        "table": "caja_vm",
        "empresa": "VM",
        "tipo": "flujo",
        "descripcion": "Movimientos de efectivo de Vitae Medical.",
        "fields": [
            ("fecha", "date", True),
            ("concepto", "text", True),
            ("categoria", "select", True, ["Ingreso", "Egreso", "Retiro", "Aporte", "Otro"]),
            ("medio", "select", True, ["Efectivo", "Transferencia", "Tarjeta", "Cheque", "Otro"]),
            ("ingreso", "money", False),
            ("egreso", "money", False),
            ("responsable", "text", False),
            ("observaciones", "textarea", False),
        ],
    },
    "Banco Galicia VM": {
        "table": "banco_galicia_vm",
        "empresa": "VM",
        "tipo": "flujo",
        "descripcion": "Movimientos bancarios de Banco Galicia pertenecientes a VM.",
        "fields": [
            ("fecha", "date", True),
            ("concepto", "text", True),
            ("tipo_movimiento", "select", True, ["Crédito", "Débito", "Transferencia", "Débito automático", "Impuesto", "Otro"]),
            ("referencia", "text", False),
            ("ingreso", "money", False),
            ("egreso", "money", False),
            ("conciliado", "bool", False),
            ("observaciones", "textarea", False),
        ],
    },
    "Cuenta Corriente VM": {
        "table": "cuenta_corriente_vm",
        "empresa": "VM",
        "tipo": "cuenta_corriente",
        "descripcion": "Cuentas por cobrar y pagar de VM.",
        "fields": [
            ("fecha", "date", True),
            ("persona_entidad", "text", True),
            ("concepto", "text", True),
            ("tipo", "select", True, ["A cobrar", "A pagar"]),
            ("importe", "money", True),
            ("pagado", "money", False),
            ("vencimiento", "date", False),
            ("estado", "select", True, ["Pendiente", "Parcial", "Pagado", "Vencido"]),
            ("observaciones", "textarea", False),
        ],
    },
    "Facturación VM": {
        "table": "facturacion_vm",
        "empresa": "VM",
        "tipo": "facturacion",
        "descripcion": "Control de facturación de procedimientos/pacientes de Vitae Medical según planilla quirófano.",
        "fields": [
            ("mes", "date", True),
            ("afiliado", "text", True),
            ("obra_social", "text", True),
            ("procedimiento", "text", True),
            ("medico_responsable", "text", True),
            ("fecha_factura", "date", False),
            ("numero_factura", "text", False),
            ("vencimiento", "date", False),
            ("fecha_pago", "text", False),
            ("valor_pesos", "money", False),
            ("valor_usd", "money", False),
            ("estado", "select", True, ["Pendiente", "Completo", "Parcial", "Vencido", "Anulado"]),
            ("observaciones", "textarea", False),
        ],
    },
    "Deudas Impositivas VMR": {
        "table": "deudas_impositivas_vmr",
        "empresa": "VMR",
        "tipo": "deuda",
        "descripcion": "IVA, Ganancias, cargas sociales, autónomos, monotributo u otros impuestos VMR.",
        "fields": [
            ("fecha", "date", True),
            ("impuesto", "select", True, ["IVA", "Ganancias", "Ingresos Brutos", "SUSS", "Monotributo", "Autónomos", "Municipal", "Otro"]),
            ("periodo", "text", True),
            ("importe", "money", True),
            ("pagado", "money", False),
            ("vencimiento", "date", True),
            ("estado", "select", True, ["Pendiente", "Parcial", "Pagado", "Plan de pago", "Vencido"]),
            ("observaciones", "textarea", False),
        ],
    },
    "Deudas Impositivas VM": {
        "table": "deudas_impositivas_vm",
        "empresa": "VM",
        "tipo": "deuda",
        "descripcion": "IVA, Ganancias, cargas sociales, autónomos, monotributo u otros impuestos VM.",
        "fields": [
            ("fecha", "date", True),
            ("impuesto", "select", True, ["IVA", "Ganancias", "Ingresos Brutos", "SUSS", "Monotributo", "Autónomos", "Municipal", "Otro"]),
            ("periodo", "text", True),
            ("importe", "money", True),
            ("pagado", "money", False),
            ("vencimiento", "date", True),
            ("estado", "select", True, ["Pendiente", "Parcial", "Pagado", "Plan de pago", "Vencido"]),
            ("observaciones", "textarea", False),
        ],
    },
    "Planes de pagos y préstamos": {
        "table": "planes_pagos_prestamos",
        "empresa": "VITAE",
        "tipo": "deuda",
        "descripcion": "Planes AFIP/ARCA, bancos, financieras, préstamos internos y externos.",
        "fields": [
            ("fecha", "date", True),
            ("empresa", "select", True, ["VMR", "VM", "VITAE"]),
            ("acreedor", "text", True),
            ("detalle", "text", True),
            ("cuotas_totales", "int", False),
            ("cuotas_pagadas", "int", False),
            ("importe_total", "money", True),
            ("saldo", "money", True),
            ("proximo_vencimiento", "date", False),
            ("estado", "select", True, ["Activo", "Finalizado", "Mora", "Refinanciado"]),
            ("observaciones", "textarea", False),
        ],
    },
    "Pagos pendientes Vitae": {
        "table": "pagos_pendientes_vitae",
        "empresa": "VITAE",
        "tipo": "pago_pendiente",
        "descripcion": "Pagos pendientes globales de la empresa.",
        "fields": [
            ("fecha", "date", True),
            ("empresa", "select", True, ["VMR", "VM", "VITAE"]),
            ("proveedor", "text", True),
            ("concepto", "text", True),
            ("importe", "money", True),
            ("pagado", "money", False),
            ("vencimiento", "date", False),
            ("prioridad", "select", True, ["Alta", "Media", "Baja"]),
            ("estado", "select", True, ["Pendiente", "Parcial", "Pagado", "Vencido"]),
            ("observaciones", "textarea", False),
        ],
    },
    "Gastos comunes": {
        "table": "gastos_comunes",
        "empresa": "VITAE",
        "tipo": "gasto",
        "descripcion": "Gastos compartidos entre VMR y VM.",
        "fields": [
            ("fecha", "date", True),
            ("rubro", "select", True, ["Luz", "Agua", "Gas", "Internet", "Limpieza", "Mantenimiento", "Sueldos", "Insumos", "Alquiler", "Otro"]),
            ("concepto", "text", True),
            ("importe", "money", True),
            ("porcentaje_vmr", "number", False),
            ("porcentaje_vm", "number", False),
            ("pagado", "bool", False),
            ("observaciones", "textarea", False),
        ],
    },
    "Vencimientos": {
        "table": "vencimientos",
        "empresa": "VITAE",
        "tipo": "vencimiento",
        "descripcion": "Calendario general de vencimientos administrativos, impositivos, contratos, habilitaciones e insumos.",
        "fields": [
            ("fecha", "date", True),
            ("empresa", "select", True, ["VMR", "VM", "VITAE"]),
            ("tipo_vencimiento", "select", True, ["Impuesto", "Servicio", "Contrato", "Habilitación", "Seguro", "Medicamento", "Mantenimiento", "Otro"]),
            ("detalle", "text", True),
            ("importe", "money", False),
            ("vencimiento", "date", True),
            ("estado", "select", True, ["Pendiente", "Realizado", "Vencido", "Reprogramado"]),
            ("observaciones", "textarea", False),
        ],
    },
    "Valores Alquileres": {
        "table": "valores_alquileres",
        "empresa": "VITAE",
        "tipo": "contrato_valor",
        "descripcion": "Control de alquileres, aumentos, valores mensuales y vigencia.",
        "fields": [
            ("fecha", "date", True),
            ("inmueble_area", "text", True),
            ("locador", "text", False),
            ("valor_mensual", "money", True),
            ("periodo", "text", True),
            ("fecha_desde", "date", False),
            ("fecha_hasta", "date", False),
            ("proximo_aumento", "date", False),
            ("estado", "select", True, ["Vigente", "Finalizado", "A renegociar"]),
            ("observaciones", "textarea", False),
        ],
    },
    "Tareas Pendientes": {
        "table": "tareas_pendientes",
        "empresa": "VITAE",
        "tipo": "tarea",
        "descripcion": "Seguimiento de tareas administrativas y operativas.",
        "fields": [
            ("fecha", "date", True),
            ("empresa", "select", True, ["VMR", "VM", "VITAE"]),
            ("tarea", "text", True),
            ("responsable", "text", False),
            ("prioridad", "select", True, ["Alta", "Media", "Baja"]),
            ("vencimiento", "date", False),
            ("estado", "select", True, ["Pendiente", "En proceso", "Finalizada", "Cancelada"]),
            ("observaciones", "textarea", False),
        ],
    },
    "Deuda total": {
        "table": "deuda_total_manual",
        "empresa": "VITAE",
        "tipo": "deuda",
        "descripcion": "Carga manual de deudas no contempladas en otros módulos. El tablero también calcula deuda total automática.",
        "fields": [
            ("fecha", "date", True),
            ("empresa", "select", True, ["VMR", "VM", "VITAE"]),
            ("acreedor", "text", True),
            ("concepto", "text", True),
            ("importe_original", "money", True),
            ("pagado", "money", False),
            ("saldo", "money", True),
            ("vencimiento", "date", False),
            ("estado", "select", True, ["Pendiente", "Parcial", "Pagado", "Vencido", "Refinanciado"]),
            ("observaciones", "textarea", False),
        ],
    },
    "Contratos": {
        "table": "contratos",
        "empresa": "VITAE",
        "tipo": "contrato",
        "descripcion": "Contratos con profesionales, proveedores, alquileres, servicios y convenios.",
        "fields": [
            ("fecha", "date", True),
            ("empresa", "select", True, ["VMR", "VM", "VITAE"]),
            ("contraparte", "text", True),
            ("tipo_contrato", "select", True, ["Profesional", "Proveedor", "Alquiler", "Servicio", "Convenio", "Otro"]),
            ("detalle", "text", True),
            ("inicio", "date", False),
            ("fin", "date", False),
            ("valor", "money", False),
            ("estado", "select", True, ["Vigente", "Vencido", "A renovar", "Finalizado"]),
            ("archivo_link", "text", False),
            ("observaciones", "textarea", False),
        ],
    },
    "Honorarios médicos": {
        "table": "honorarios_medicos",
        "empresa": "VITAE",
        "tipo": "honorario",
        "descripcion": "Honorarios por médico, prestación, estado de pago y empresa.",
        "fields": [
            ("fecha", "date", True),
            ("empresa", "select", True, ["VMR", "VM", "VITAE"]),
            ("medico", "text", True),
            ("paciente", "text", False),
            ("procedimiento", "text", True),
            ("importe", "money", True),
            ("pagado", "money", False),
            ("fecha_pago", "date", False),
            ("estado", "select", True, ["Pendiente", "Parcial", "Pagado"]),
            ("observaciones", "textarea", False),
        ],
    },
    "Gine Vitae": {
        "table": "gine_vitae",
        "empresa": "VM",
        "tipo": "unidad_medica",
        "descripcion": "Gestión de pacientes, prácticas, derivaciones y cirugías de la unidad Gine Vitae.",
        "fields": [
            ("fecha", "date", True),
            ("paciente", "text", True),
            ("dni", "text", False),
            ("telefono", "text", False),
            ("medico", "text", False),
            ("obra_social", "text", False),
            ("practica", "select", True, ["Consulta", "Control anual", "PAP", "Colposcopía", "HPV", "Ecografía", "Histeroscopía", "LEEP", "DIU", "Cirugía", "Otro"]),
            ("estado", "select", True, ["Pendiente", "Turno dado", "Realizado", "Derivado a quirófano", "Cancelado"]),
            ("importe", "money", False),
            ("cobrado", "money", False),
            ("proxima_accion", "text", False),
            ("observaciones", "textarea", False),
        ],
    },
}